version: 0.0
os: linux
files:
  - source: /
    destination: /opt/bitnami/apache-tomcat/webapps/SpringRestfulExample/
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/change_permissions.sh
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/cleanup.sh
      timeout: 60
      runas: root
 